runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:gR1pMq75wD/LS5sQ9HM++41TaQnhNNL5KlcrCIos/fI=
  STORAGE_DIR: /tmp
